dictionary/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from number_registry import views
from number_registry import views as core_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', views.index, name='index'),
    #url(r'', include('number_registry.urls')),
    #url(r'^reserve_cart$', views.reserve_cart,  name='reserve_cart'),
    #url(r'^review_cart/$', views.review_cart,  name='review_cart'),
    #url(r'^reserve$', views.reserve_new,  name='reserve_new'),
    url(r'^signup/$', core_views.signup, name='signup'),
    #url(r'^login/$', auth_views.login, name='login'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- For Social
    ] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

lib/social_django/urls.py
"""URLs module"""
from django.conf import settings
from django.conf.urls import url

from social_core.utils import setting_name
from . import views


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

app_name = 'social'

urlpatterns = [
    # authentication / association
    url(r'^login/(?P<backend>[^/]+){0}$'.format(extra), views.auth,
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), views.complete,
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), views.disconnect,
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>\d+){0}$'
        .format(extra), views.disconnect, name='disconnect_individual'),
]

number_registry/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.entry_list, name='entry_list'),
    #url(r'^reserve', views.reserve_new, name='reserve_new'),
	#url(r'^ordered/', views.entry_list, name='entry_list_ordered'),
]

lib/django/contrib/gis/db/backends/base/models.py
from django.contrib.gis import gdal


class SpatialRefSysMixin:
    """
    The SpatialRefSysMixin is a class used by the database-dependent
    SpatialRefSys objects to reduce redundant code.
    """
    @property
    def srs(self):
        """
        Return a GDAL SpatialReference object.
        """
        # TODO: Is caching really necessary here?  Is complexity worth it?
        if hasattr(self, '_srs'):
            # Returning a clone of the cached SpatialReference object.
            return self._srs.clone()
        else:
            # Attempting to cache a SpatialReference object.

            # Trying to get from WKT first.
            try:
                self._srs = gdal.SpatialReference(self.wkt)
                return self.srs
            except Exception as e:
                msg = e

            try:
                self._srs = gdal.SpatialReference(self.proj4text)
                return self.srs
            except Exception as e:
                msg = e

            raise Exception('Could not get OSR SpatialReference from WKT: %s\nError:\n%s' % (self.wkt, msg))

    @property
    def ellipsoid(self):
        """
        Return a tuple of the ellipsoid parameters:
        (semimajor axis, semiminor axis, and inverse flattening).
        """
        return self.srs.ellipsoid

    @property
    def name(self):
        "Return the projection name."
        return self.srs.name

    @property
    def spheroid(self):
        "Return the spheroid name for this spatial reference."
        return self.srs['spheroid']

    @property
    def datum(self):
        "Return the datum for this spatial reference."
        return self.srs['datum']

    @property
    def projected(self):
        "Is this Spatial Reference projected?"
        return self.srs.projected

    @property
    def local(self):
        "Is this Spatial Reference local?"
        return self.srs.local

    @property
    def geographic(self):
        "Is this Spatial Reference geographic?"
        return self.srs.geographic

    @property
    def linear_name(self):
        "Return the linear units name."
        return self.srs.linear_name

    @property
    def linear_units(self):
        "Return the linear units."
        return self.srs.linear_units

    @property
    def angular_name(self):
        "Return the name of the angular units."
        return self.srs.angular_name

    @property
    def angular_units(self):
        "Return the angular units."
        return self.srs.angular_units

    @property
    def units(self):
        "Return a tuple of the units and the name."
        if self.projected or self.local:
            return (self.linear_units, self.linear_name)
        elif self.geographic:
            return (self.angular_units, self.angular_name)
        else:
            return (None, None)

    @classmethod
    def get_units(cls, wkt):
        """
        Return a tuple of (unit_value, unit_name) for the given WKT without
        using any of the database fields.
        """
        return gdal.SpatialReference(wkt).units

    @classmethod
    def get_spheroid(cls, wkt, string=True):
        """
        Class method used by GeometryField on initialization to
        retrieve the `SPHEROID[..]` parameters from the given WKT.
        """
        srs = gdal.SpatialReference(wkt)
        sphere_params = srs.ellipsoid
        sphere_name = srs['spheroid']

        if not string:
            return sphere_name, sphere_params
        else:
            # `string` parameter used to place in format acceptable by PostGIS
            if len(sphere_params) == 3:
                radius, flattening = sphere_params[0], sphere_params[2]
            else:
                radius, flattening = sphere_params
            return 'SPHEROID["%s",%s,%s]' % (sphere_name, radius, flattening)

    def __str__(self):
        """
        Return the string representation, a 'pretty' OGC WKT.
        """
        return str(self.srs)

number_registry/models.py
from django.db import models
from django.utils import timezone

#these are for validating errors
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

#validate a number is divisable by 3  
#TODO: Add more descriptive text 
def validate_div3(value):
    if value % 3 != 0:
        raise ValidationError(
            _('%(value)s is not divisable by 3.'),
            params={'value': value},
        )
#Checks the database to see if there is an existing record with the same name
#BUG:  Cannot update existing entries in the admin page.  
def validateUniqueName(value):
	lookup = Entry.objects.filter(name=value).exists()
	if lookup == True:
		raise ValidationError(
			_('We are sorry, but "%(value)s" has already been registered.  Please pick a different name for your number.'),
			params={'value': value},
			)
#Checks the database to see if the number has been registered.
#BUG:  Cannot update existing entries in the admin page.
def validateUniqueNumber(value):
	lookup = Entry.objects.filter(number=value).exists()
	if lookup == True:
		raise ValidationError(
			_('We are sorry, but "%(value)s" has already been registered.  Please pick a different number to register.  Luckily, you have an infinite number to choose from!'),
			params={'value': value},
			)

# Model for Adding a new number to the dictoinary
class Entry(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, validators=[validateUniqueName])
    number = models.BigIntegerField(validators=[validate_div3, validateUniqueNumber])
    comment = models.TextField(blank=True)
    dedication = models.CharField(blank=True, max_length=100)
    created_date = models.DateTimeField(
            default=timezone.now)
    famous = models.BooleanField(default=False)
    premium = models.BooleanField(default=False)
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()

#Model for user's carts
#TODO:  Replace the CASCADE statement (Or just disable users via a flag?)
class Cart(models.Model):
	buyer = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	desiredname = models.CharField(max_length=100, validators=[validateUniqueName])
	desirednumber = models.BigIntegerField(validators=[validate_div3, validateUniqueNumber])
	desiredcomment = models.TextField(blank=True)
	desireddedication = models.CharField(blank=True, max_length=100)
	created_date = models.DateTimeField(
            default=timezone.now)

	def publish(self):
		self.published_date = timezone.now()
		self.save()
	
	def __str__(self): # __str__ for Python 3, __unicode__ for Python 2
		return self.name

number_registry/forms.py
from django import forms
from .models import Entry, Cart
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#these are for validating errors
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _




class Reserve(forms.ModelForm):	
	class Meta:
		model = Entry
		fields = ('name', 'number', 'comment', 'dedication',)

class ReserveCart(forms.ModelForm):	
	class Meta:
		model = Cart
		fields = ('desiredname', 'desirednumber', 'desiredcomment', 'desireddedication',)

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

number_registry/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

from .models import Entry, Cart
from .forms import Reserve, SignUpForm, ReserveCart

# This is the homepage
def index(request):
	return render(request, 'number_registry/index.html')

# Lists all known entries.  (for now)
def entry_list(request):
	entries = Entry.objects.order_by('number')
	return render(request, 'number_registry/entry_list.html', {'entries':entries})

# Creates a new reservation.  NOTE:  This needs to write to the cart and not the registry!
#Will need to be depricated!
def reserve_new(request):
	if request.method == "POST":
		form = Reserve(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.owner = request.user
			post.save()
			return redirect('entry_list')
	else:
		form = Reserve()

	return render(request, 'number_registry/reserve_number.html', {'form': form})

#Adding reservations to the cart
def reserve_cart(request):
	if request.method == "POST":
		form = ReserveCart(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.buyer = request.user
			post.save()
			return redirect('review_cart')
	else:
		form = ReserveCart()

	return render(request, 'number_registry/reserve_cart.html', {'form': form})

# Shows cart items to user
@login_required
def review_cart(request):
		cartContents = Cart.objects.filter(buyer_id=request.user)
		return render(request, 'number_registry/review_cart.html', {'cartContents':cartContents})


# New User creation page.  Facebook login works!
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'number_registry/signup.html', {'form': form})

def logout_view(request):
	logout(request)
	return redirect('/')


@login_required
def home(request):
    return render(request, 'number_registry/home.html')

number_registry/templates/number_registry/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>This is a list of all known numbers!</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/numreg.css' %}">
</head>
<body>
    <div class="page-header">
        <h1><a href="/">The Number Registry</a></h1>
        <h2><a href="/reserve">Reserve</a></h2>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

number_registry/templates/number_registry/entry_list.html
<!DOCTYPE html>
<html >
<head>
  <!-- Site made with Mobirise Website Builder v4.8.1, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.8.1, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo2.png" type="image/x-icon">
  <meta name="description" content="Web Site Maker Description">
  <title>Entry_list</title>
  <link rel="stylesheet" href="assets/web/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="assets/tether/tether.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="assets/animatecss/animate.min.css">
  <link rel="stylesheet" href="assets/datatables/data-tables.bootstrap4.min.css">
  <link rel="stylesheet" href="assets/dropdown/css/style.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
  <link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css">
  
  
  
</head>
<body>
  <section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-7">

    

    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="index.html">The Number Registry</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="https://mobirise.com"><span class="mbri-shopping-cart mbr-iconfont mbr-iconfont-btn"></span>
                        
                        Cart</a>
                </li><li class="nav-item"><a class="nav-link link text-white display-4" href="https://mobirise.com"><span class="mbri-laptop mbr-iconfont mbr-iconfont-btn"></span>
                        
                        Account</a></li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="https://mobirise.com">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                        About Us
                    </a>
                </li></ul>
            
        </div>
    </nav>
</section>

<section class="engine"><a href="https://mobiri.se/u">bootstrap website templates</a></section><section class="section-table cid-qYGn4FnBvt" id="table1-a">

  
  
  <div class="container container-table">
      <h2 class="mbr-section-title mbr-fonts-style align-center pb-3 display-2">
          All Numbers</h2>
      <h3 class="mbr-section-subtitle mbr-fonts-style align-center pb-5 mbr-light display-5">From here, you can see all the numbers that have been registered in our database.</h3>
      <div class="table-wrapper">
        <div class="container">
          <div class="row search">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <div class="dataTables_filter">
                  <label class="searchInfo mbr-fonts-style display-7">Search:</label>
                  <input class="form-control input-sm" disabled="">
                </div>
            </div>
          </div>
        </div>

        <div class="container scroll">
          <table class="table isSearch" cellspacing="0">
            <thead>
              <tr class="table-heads ">
                  
                  
                  
                  
              <th class="head-item mbr-fonts-style display-7">
                      NUMBER</th><th class="head-item mbr-fonts-style display-7">
                      NAME</th><th class="head-item mbr-fonts-style display-7">
                      COMMENT</th></tr>
            </thead>

            <tbody>
              
              {% extends 'number_registry/base.html' %}
              {% block content %}
               {% for entry in entries %}
            <tr> 
                
                
                
                
              <td class="body-item mbr-fonts-style display-7">{{ entry.number }}</td><td class="body-item mbr-fonts-style display-7">{{ entry.name }}</td><td class="body-item mbr-fonts-style display-7">{{ entry.comment }}</td></tr><tr>
                
             {% endfor %}
             {% endblock %}   
                
                
          </tbody>
          </table>
        </div>
        <div class="container table-info-container">
          <div class="row info">
            <div class="col-md-6">
              <div class="dataTables_info mbr-fonts-style display-7">
                <span class="infoBefore">Showing</span>
                <span class="inactive infoRows"></span>
                <span class="infoAfter">entries</span>
                <span class="infoFilteredBefore">(filtered from</span>
                <span class="inactive infoRows"></span>
                <span class="infoFilteredAfter"> total entries)</span>
              </div>
            </div>
            <div class="col-md-6"></div>
          </div>
        </div>
      </div>
    </div>
</section>


  <script src="assets/web/assets/jquery/jquery.min.js"></script>
  <script src="assets/popper/popper.min.js"></script>
  <script src="assets/tether/tether.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/smoothscroll/smooth-scroll.js"></script>
  <script src="assets/touchswipe/jquery.touch-swipe.min.js"></script>
  <script src="assets/viewportchecker/jquery.viewportchecker.js"></script>
  <script src="assets/datatables/jquery.data-tables.min.js"></script>
  <script src="assets/datatables/data-tables.bootstrap4.min.js"></script>
  <script src="assets/dropdown/js/script.min.js"></script>
  <script src="assets/theme/js/script.js"></script>
  
  
 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i></i></a></div>
    <input name="animation" type="hidden">
  </body>
</html>

number_registry/templates/number_registry/index.html
{% extends 'number_registry/base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>

  <!-- Site made with Mobirise Website Builder v4.8.1, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.8.1, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static "images/logo2.png" type="image/x-icon">
  <meta name="description" content="">
  <title>The Number Registry</title>
  <link rel="stylesheet" href="{% static "web/assets/mobirise-icons/mobirise-icons.css" %}"/>
  <link rel="stylesheet" href="{% static "tether/tether.min.css" %}"/>
  <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}"/>
  <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap-grid.min.css" %}"/>
  <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap-reboot.min.css" %}"/>
  <link rel="stylesheet" href="{% static "animatecss/animate.min.css" %}"/>
  <link rel="stylesheet" href="{% static "dropdown/css/style.css" %}"/>
  <link rel="stylesheet" href="{% static "theme/css/style.css" %}"/>
  <link rel="stylesheet" href="{% static "mobirise/css/mbr-additional.css" %}" type="text/css">
  
  
  
</head>
<body>
  <section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-0">

    

    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href=" ">The Number Registry</a></span>
            </div>
        </div>
       <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="review_cart"><span class="mbri-shopping-cart mbr-iconfont mbr-iconfont-btn"></span>
                        
                        Cart</a>
                </li><li class="nav-item"><a class="nav-link link text-white display-4" href="https://mobirise.com"><span class="mbri-laptop mbr-iconfont mbr-iconfont-btn"></span>
                        
                        Account</a></li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="https://mobirise.com">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                        About Us
                    </a>
                </li>--></ul>
            
        </div>
    </nav>
</section>

<section class="engine"><a href="https://mobiri.se/u">bootstrap html templates</a></section><section class="cid-qTkA127IK8 mbr-fullscreen mbr-parallax-background" id="header2-1">

    

    <div class="mbr-overlay" style="opacity: 0.6; background-color: rgb(118, 118, 118);"></div>

    <div class="container align-center">
        <div class="row justify-content-md-center">
            <div class="mbr-white col-md-10">
                <h1 class="mbr-section-title mbr-bold pb-3 mbr-fonts-style display-1">The Number Registry</h1>
                
                <p class="mbr-text pb-3 mbr-fonts-style display-5">Coming soon</p>
                <!--<div class="mbr-section-btn"><a class="btn btn-md btn-secondary display-4" href="reserve_number.html">Register</a>
                    <a class="btn btn-md btn-white-outline display-4" href="https://mobirise.com">Browse Numbers</a></div>-->
            </div>
        </div>
    </div>
    <div class="mbr-arrow hidden-sm-down" aria-hidden="true">
        <a href="#next">
            <i class="mbri-down mbr-iconfont"></i>
        </a>
    </div>
</section>

<section class="header9 cid-qYGfGd4Gjk mbr-fullscreen mbr-parallax-background" id="header9-3">

    

    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(0, 0, 0);">
    </div>

    <div class="container">
        <div class="media-container-column mbr-white col-md-8">
            <h1 class="mbr-section-title align-left mbr-bold pb-3 mbr-fonts-style display-1">A "1" followed by 6 zeros is a "million".</h1>
            <h3 class="mbr-section-subtitle align-left mbr-light pb-3 mbr-fonts-style display-2">A "1" followed by 9 zeros is a "billion".</h3>
            <p class="mbr-text align-left pb-3 mbr-fonts-style display-5">A "1" followed by 786 zeros could be whatever you want.</p>
           <!-- <div class="mbr-section-btn align-left"><a class="btn btn-md btn-primary display-4" href="https://mobirise.com">LEARN MORE</a></div>-->
        </div>
    </div>

   <!-- <div class="mbr-arrow hidden-sm-down" aria-hidden="true">
        <a href="#next">
            <i class="mbri-down mbr-iconfont"></i>
        </a>
    </div>-->
</section>


  <script src="{% static "web/assets/jquery/jquery.min.js" %}"/></script>
  <script src="{% static "popper/popper.min.js" %}"/></script>
  <script src="{% static "tether/tether.min.js" %}"/></script>
  <script src="{% static "bootstrap/js/bootstrap.min.js" %}"/></script>
  <script src="{% static "smoothscroll/smooth-scroll.js" %}"/></script>
  <script src="{% static "touchswipe/jquery.touch-swipe.min.js" %}"/></script>
  <script src="{% static "viewportchecker/jquery.viewportchecker.js" %}"/></script>
  <script src="{% static "parallax/jarallax.min.js" %}"/></script>
  <script src="{% static "dropdown/js/script.min.js" %}"/></script>
  <script src="{% static "theme/js/script.js" %}"/></script>
  
  
 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i></i></a></div>
    <input name="animation" type="hidden">

{% endblock %}

number_registry/templates/number_registry/signup.html
{% extends 'number_registry/base.html' %}

{% block content %}


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '686692548334936',
      cookie     : true,
      xfbml      : true,
      version    : 'v3.0'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
--OR

  <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>

{% endblock %}